### ISSUE TITLE
Select specific "year_range"  

### ISSUE THREAD

**Issue by quasar25** [tropycal/tropycal#127]
Hello, 

I have a question for "year_range" of gridded_stats in gridded analysis. 
I'd like to run the data by selecting specific years(from 1990 to 2018 only) from the whole data, but the plot for the difference is drawn, but I can't select specific years. I'd like to plot the maximum wind speed for the data from 1990 to 2018 with Gridded Analyzes, not the maximum wind speed for the entire data period (1845-2021). I would like to ask if there is a way to solve this.

Sincerely, Thank you.

**Comment by tomerburg** [comment]
Apologies for only now getting around to this issue - the formerly broken documentation has been updated since your original post, so a good place to start would be referring to the ``gridded_stats()`` section:

https://tropycal.github.io/tropycal/api/generated/tropycal.tracks.TrackDataset.gridded_stats.html#tropycal.tracks.TrackDataset.gridded_stats

Sounds like from your description you'd want to add an argument ``year_range=(1990,2018)`` when calling ``gridded_stats()``.

**Comment by tomerburg** [comment]
In the meantime I will be closing this issue - feel free to reopen if the suggestion above didn't solve your issue.
