### ISSUE TITLE
CRS error

### ISSUE THREAD

**Issue by mgmanalili** [tropycal/tropycal#130]
Below snippet gives me CRS traceback error

`ibtracs = tracks.TrackDataset(basin='south_indian',source='ibtracs',ibtracs_mode='jtwc_neumann',catarina=True)
ibtracs.plot_storm(('idai',2019),return_ax=True)`

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-c15a6df4236e> in <module>
----> 1 ibtracs.plot_storm(('idai',2019),return_ax=True)

~/miniconda2/envs/adamf/lib/python3.7/site-packages/tropycal/tracks/dataset.py in plot_storm(self, storm, domain, plot_all, ax, return_ax, cartopy_proj, save_path, prop, map_prop)
   1101                 self.plot_obj.create_cartopy(proj='PlateCarree',central_longitude=180.0)
   1102             else:
-> 1103                 self.plot_obj.create_cartopy(proj='PlateCarree',central_longitude=0.0)
   1104         else:
   1105             self.plot_obj.proj = cartopy_proj

~/miniconda2/envs/adamf/lib/python3.7/site-packages/tropycal/plot/plot.py in create_cartopy(self, proj, mapobj, **kwargs)
     69         #Initialize an instance of cartopy if not passed
     70         if mapobj == None:
---> 71             self.proj = getattr(ccrs, proj)(**kwargs)
     72         else:
     73             self.proj = mapobj

NameError: name 'ccrs' is not defined

**Comment by nicholasoxford** [comment]
I am having the same issue.
![Screen Shot 2021-09-08 at 7 07 12 PM](https://user-images.githubusercontent.com/51415676/132597131-11e1d251-fe21-4a27-ab6b-163b4fb554ef.png)

**Comment by nicholasoxford** [comment]
@tomerburg I have seen you made some commits recently to the plot file. I would love to learn more about this repo so let me know if you want to collaborate on the issue!

**Comment by tomerburg** [comment]
Thanks for opening the issue and including the full traceback error message! In the ``plot/plot.py`` file, lines 13-19 attempt to import cartopy, including importing ccrs which is where both of the images above crash. This suggests to me you may not have cartopy installed in your environments, or that there may be some sort of an issue with your version of cartopy such that importing it fails. Of course if that's not the case I'd be happy to look further into it.

This would also depend on how you installed tropycal; cartopy is a requirement when installing via pip (or as of v0.3, via conda-forge), though it's also possible to install directly via the source code in which case it should be able to install without cartopy. This was built in order to allow analyses for people who don't have cartopy in their environments, though this also means if you installed tropycal this way, you can't use any of the plotting functionality.

**Comment by nicholasoxford** [comment]
I tried installing cartopy as well, but with no success. I also tried changing the way the import works in the plot file with little success. I'll look into installing Tropycal from source.

[Link to notebook](https://colab.research.google.com/drive/1xvWKUMVQZZO9U_NVB_aM-ePySg4Qo1fk?usp=sharing)

**Comment by nicholasoxford** [comment]
@tomerburg, thank you again for your help. I am a javascript / c# guy so forgive me for my python ignorance. After trying a bunch of things out I still seem stuck getting plot to work. I even imported from source, and tried adding it to my sys path with no success. Let me know if you have any ideas!

<img width="1763" alt="Screen Shot 2021-09-10 at 10 07 41 AM" src="https://user-images.githubusercontent.com/51415676/132866746-df5e7125-bffe-4b20-a322-0f11e1284506.png">

**Comment by tomerburg** [comment]
As this issue has been referenced with continued discussion in a separate issue (#134), I will be closing this issue. Feel free to reopen should a similar issue come up.
