### ISSUE TITLE
to_dataframe() did not work for north_indian

### ISSUE THREAD

**Issue by GC-OCEAN** [tropycal/tropycal#160]
`nio = tracks.TrackDataset(basin='north_indian',source='ibtracs',ibtracs_mode='jtwc',catarina=True)`
`nio`

<tropycal.tracks.Dataset>
Dataset Summary:
    Basin:             north_indian
    Source:            ibtracs, jtwc
    Number of storms:  772
    Maximum wind:      150 knots (Ida 1954)
    Minimum pressure:  898 hPa (Gonu 2007)
    Year range:        1932 — 2022

`nio.to_dataframe()`

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [57], in <cell line: 2>()
      1 nio = tracks.TrackDataset(basin='north_indian',source='ibtracs',ibtracs_mode='jtwc',catarina=True)
----> 2 nio.to_dataframe()

File ~/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/tropycal/tracks/dataset.py:3234, in TrackDataset.to_dataframe(self)
   3230 #Iterate over all seasons in the TrackDataset object
   3231 for season in range(start_season,end_season+1):
   3232 
   3233     #Get season summary
-> 3234     season_summary = self.get_season(season).summary()
   3235     if len(season_summary['id']) == 0: continue
   3237     #Add information to dict

File ~/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/tropycal/tracks/dataset.py:1443, in TrackDataset.get_season(self, year, basin)
   1441 #Retrieve season object(s)
   1442 if isinstance(year,(int,np.int,np.integer,float,np.floating)):
-> 1443     return self.__retrieve_season(year,basin)
   1444 else:
   1445     return_season = self.__retrieve_season(year[0],basin)

File ~/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/tropycal/tracks/dataset.py:1399, in TrackDataset.__retrieve_season(self, year, basin)
   1395             #basin_list.append(max(set(self.data[key]['wmo_basin']), key=self.data[key]['wmo_basin'].count))
   1396         
   1397 #Error check
   1398 if len(season_dict) == 0:
-> 1399     raise RuntimeError("No storms were identified for the given year in the given basin.")
   1401 #Add attributes
   1402 first_key = [k for k in season_dict.keys()][0]

RuntimeError: No storms were identified for the given year in the given basin.

**Comment by tomerburg** [comment]
Thanks for opening this issue! I was able to replicate your error message, which turned out to be from Season objects raising an error message if a requested year does not have any storms. Normally tropical cyclone datasets are continuous, but in the North Indian basin there is a storm entry in 1932 but with a multi-year gap afterwards until the next entry.

I just fixed this for the upcoming v0.5 release and was able to produce results for this bug. I'll close this issue when v0.5 is released. Thanks again for notifying us!
![image](https://user-images.githubusercontent.com/23174572/178285038-861d46c9-25bb-4bc6-a9aa-0887858469b9.png)
