### ISSUE TITLE
Tropycal don´t plot

### ISSUE THREAD

**Issue by elierpf** [tropycal/tropycal#176]
I tried to run all the examples on the project, loading HURDAT data from a local source and none plot and neither send any error

Running on Tropiycal 0.6 on Ubuntu 20.04 installed via pip, with pyhton 3.8 version, with all the dependencies update to the latest version.

**Output of pip3 install --upgrade tropycal**
Requirement already up-to-date: tropycal in /usr/local/lib/python3.8/dist-packages (0.6)
Requirement already satisfied, skipping upgrade: numpy>=1.14.3 in /usr/local/lib/python3.8/dist-packages (from tropycal) (1.23.4)
Requirement already satisfied, skipping upgrade: networkx>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from tropycal) (2.8.7)
Requirement already satisfied, skipping upgrade: requests>=2.22.0 in /usr/lib/python3/dist-packages (from tropycal) (2.22.0)
Requirement already satisfied, skipping upgrade: pyshp>=2.1 in /usr/lib/python3/dist-packages (from tropycal) (2.1.0)
Requirement already satisfied, skipping upgrade: scipy>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from tropycal) (1.9.3)
Requirement already satisfied, skipping upgrade: matplotlib>=2.2.2 in /usr/local/lib/python3.8/dist-packages (from tropycal) (3.6.1)
Requirement already satisfied, skipping upgrade: pandas>=0.23.0 in /usr/lib/python3/dist-packages (from tropycal) (0.25.3)
Requirement already satisfied, skipping upgrade: xarray>=0.10.7 in /usr/lib/python3/dist-packages (from tropycal) (0.15.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2.2->tropycal) (2.8.1)
Requirement already satisfied, skipping upgrade: contourpy>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2.2->tropycal) (1.0.5)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /usr/lib/python3/dist-packages (from matplotlib>=2.2.2->tropycal) (1.0.1)
Requirement already satisfied, skipping upgrade: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2.2->tropycal) (4.38.0)
Requirement already satisfied, skipping upgrade: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib>=2.2.2->tropycal) (7.0.0)
Requirement already satisfied, skipping upgrade: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib>=2.2.2->tropycal) (2.4.6)
Requirement already satisfied, skipping upgrade: packaging>=20.0 in /usr/lib/python3/dist-packages (from matplotlib>=2.2.2->tropycal) (20.3)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /usr/lib/python3/dist-packages (from matplotlib>=2.2.2->tropycal) (0.10.0)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib>=2.2.2->tropycal) (1.14.0)

**Comment by tomerburg** [comment]
Can you provide more specific details on what doesn't work? What line(s) of code are not working as intended when you try to generate plots? Does it work if you try to save the images locally?

**Comment by mrshll** [comment]
I think I'm encountering something similar to #134 and this issue, and I'll just add my observations here since the original issue was pretty open-ended

First off, awesome library. Very impressive visualizations and always amazed when folks interop with multiple agencies' sources.

I'm going the `pip` route so it's possible that's the source of the issues between the three reports here. 

<details><summary>pip freeze output</summary>
<p>

```
(.venv)  ◰³ .venv  ~/w/d/experiments  pip freeze                                                   47.4s  Tue 03 Oct 2023 03:34:47 PM EDT
Cartopy==0.22.0
certifi==2023.7.22
charset-normalizer==3.3.0
contourpy==1.1.1
cycler==0.12.0
fonttools==4.43.0
idna==3.4
kiwisolver==1.4.5
matplotlib==3.8.0
networkx==3.1
numpy==1.26.0
packaging==23.2
pandas==2.1.1
Pillow==10.0.1
pyparsing==3.1.1
pyproj==3.6.1
pyshp==2.3.1
python-dateutil==2.8.2
pytz==2023.3.post1
requests==2.31.0
scipy==1.11.3
setuptools==68.2.2
shapely==2.0.1
six==1.16.0
tropycal==1.2.1
tzdata==2023.3
urllib3==2.0.6
xarray==2023.9.0
```

</p>
</details> 

Everything seems to be functioning well, it's just the plotting that doesn't "show up." I did a separate test to make sure cartopy was functioning as expected, which worked just fine.

<details><summary>test to see if cartopy functioning</summary>
<p>

```
from matplotlib import plot as plt
import cartopy.crs as ccrs
import cartopy.feature as cf
ax = plt.axes(projection = ccrs.Mercator())
ax.add_feature(cf.COASTLINE)
plt.show()
```

![image](https://github.com/tropycal/tropycal/assets/339996/f0e97907-0f6a-4dfc-b19b-4994acdd1776)

</p>
</details> 

I think it might be something in https://github.com/tropycal/tropycal/blob/master/src/tropycal/plot/plot.py but haven't had time to look closely at the source. Have you heard any similar issues regarding pip & plots not showing up? 

Thanks :)
