### ISSUE TITLE
commands listed in index don't exist?

### ISSUE THREAD

**Issue by judydickey** [tropycal/tropycal#74]
import tropycal.tracks as tracks
import datetime as dt
hurdat_atl = tracks.TrackDataset(basin='north_atlantic',source='hurdat',include_btk=False)
tracks.filter_storms(subset_domain=(80, 98, 24, 32), doInterp=False, return_keys=True)

returns:
AttributeError: module 'tropycal.tracks' has no attribute 'filter_storms'

**Comment by tomerburg** [comment]
Thanks for the issue. This is a problem with the usage of the function. When you call this in your first line:

`hurdat_atl = tracks.TrackDataset(basin='north_atlantic',source='hurdat',include_btk=False)`

You create an instance of a TrackDataset object and store it in the "hurdat_atl" variable. Therefore all the methods associated with TrackDataset can now be accessed via the "hurdat_atl" variable. You would thus change your second line from this:

`tracks.filter_storms(subset_domain=(80, 98, 24, 32), doInterp=False, return_keys=True)`

To this:

`hurdat_atl.filter_storms(subset_domain=(80, 98, 24, 32), doInterp=False, return_keys=True)`

Since this is a resolved user issue, I'm closing the issue. Please feel free to send us any other questions by email or opening an issue (https://tropycal.github.io/tropycal/support.html).
