### ISSUE TITLE
Realtime cyclone informations over Indian ocean are not being retrived...

### ISSUE THREAD

**Issue by wxguy** [tropycal/tropycal#91]
I am trying to get current active (as on 02-06-20:1750h) track info for Cyclone "Nisarga" (WMO code name) and the same info is available at http://hurricanes.ral.ucar.edu/realtime/plots/northindian/2020/io932020/.  I have the following two lines of code to list all active cyclone to check if your module picks up:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import tropycal.tracks as tracks
from tropycal.realtime import Realtime

tracks_ist = Realtime()
print(tracks_ist.list_active_storms())
```

It gave the following output:-

```
λ python track.py
--> Starting to read in current storm data
--> Completed reading in current storm data (25.32 seconds)
['AL032020']
```

Unfortunately, the module gave only active cyclone over north Atlantic cyclone . It is really disappointing to see the module's inability to retrieve information about cyclone over Indian Ocean. Is it expected behaviors of the module or am I doing something wrong. Earlier, I did try to retrieve other past cyclone info https://github.com/tropycal/tropycal/issues/90 which also returned nothing.

**Comment by wxguy** [comment]
Found a bug in the realtime.py file in this line `search_pattern = f'b[isw][ohp][01234][0123456789]{current_year}.dat'`. The current Indian Ocean cyclone id is IO932020 where as search pattern restrict only up to search for 4. Changing the line to  `search_pattern = f'b[isw][ohp][012349][0123456789]{current_year}.dat'` solved the problem. But that lead to another issue. While retrieving cyclone forecast summary using `get_forecast_realtime()` method, it is trying to download *.sum file from https://www.nrlmry.navy.mil/atcf_web/docs/current_storms/. However, there are no files, except one, ending with *.sum. Please look in to this issue...

**Comment by wxguy** [comment]
Next bug. Trying to get real time infor of the storm IO932020 using `RealtimeStorm.get_realtime_info()`. But it gave this error `NameError: name 'convert_category' is not defined`. Up on investigation, I could not get any function named `convert_category` from any file imported in `storm.py` under realtime directory.

**Comment by tomerburg** [comment]
Hi there - thank you for reporting these issues to us! Starting off from the first issue onward:

- This is not necessarily a bug/error, but an inherent limitation in the data source used. We retrieve storms classified as tropical cyclones from the Joint Typhoon Warning Center (JTWC) in realtime, even if they may be considered tropical cyclones by other agencies (such as the IMO in this instance). Since the first character is a 9, this implies it's classified as an invest by the JTWC, and we currently do not support invest handling, though this capability will be added in the future.

- I'm unable to find where this function is being called from. You could be using an outdated version of Tropycal (compared to now), as our latest update removed that. Please check if you still encounter this error.
