### ISSUE TITLE
Data retrieve refused

### ISSUE THREAD

**Issue by cynthiazeng** [tropycal/tropycal#97]
Hi, when I tried to retrieve forecast data, I have received this error message, saying maximum retrieval has been reached: can I ask if there is a way to fix this error?

Thank you!

![image](https://user-images.githubusercontent.com/41646427/90243854-a270fe80-ddfd-11ea-98c6-8211ae930e5f.png)

**Comment by tomerburg** [comment]
Thanks for opening the issue! I would speculate this could be due to attempting to connect too many times to the data on the NHC server, or perhaps a problem on the NHC server side of things. What was the code that you ran that resulted in this error? Or more specifically, what function did you call that triggered the error? This would help in seeing if this is something that can be improved on our end.

**Comment by cynthiazeng** [comment]
Hi Tomer,

Thanks for your reply.  I think the problem was due to calling the "hurdat_atl = tracks.TrackDataset(basin='north_atlantic',source='hurdat',include_btk=False)" line for too many times. The problem went away after I waited for some time. I hope this feedback is helpful. 

Thanks for your help!
